Q1. Write a code to reverse a string.

In [18]:
a="string"
reverse_of_a = a[::-1]
reverse_of_a

'gnirts'

Q2. Write a code to count the number of vowels in a string.

In [20]:
a=input("enter a string : ")
vowels = ("aeiou")
no_of_vowels = 0
for i in a:
  for j in vowels:
    if i==j:
      no_of_vowels += 1
print("the number of vowels in the string is: ",no_of_vowels)

enter a string : himalayas
the number of vowels in the string is:  4

Q3. Write a code to check if a given strings is a palindrome or not.

In [ ]:
string1= input("string : ")
if string1[::1]==string1[::-1]:
  print("the string is a palindrome")
else:
  print("the string is not a palindrome")

string : madam
the string is a palindrome

In [ ]:
string1= input("string : ")
if string1[::1]==string1[::-1]:
  print("the string is a palindrome")
else:
  print("the string is not a palindrome")

string : google
the string is not a palindrome

Q4. Write a code to check if two given strings are anagrams of each other.

In [ ]:
#eg; "listen" is anagram of "silent"
string1 = input("enter the 1st string : ")
string2 = input("enter the 2nd string : ")
if sorted(string1) == sorted(string2):
  print("they are anagrams of each other")
else:
  print("they are not anagrams")

enter the 1st string : dog
enter the 2nd string : god
they are anagrams of each other

In [ ]:
#eg; "listen" is anagram of "silent"
string1 = input("enter the 1st string : ")
string2 = input("enter the 2nd string : ")
if sorted(string1) == sorted(string2):
  print("they are anagrams of each other")
else:
  print("they are not anagrams")

enter the 1st string : shira
enter the 2nd string : rashi
they are anagrams of each other

In [ ]:
#eg; "listen" is anagram of "silent"
string1 = input("enter the 1st string : ")
string2 = input("enter the 2nd string : ")
if sorted(string1) == sorted(string2):
  print("they are anagrams of each other")
else:
  print("they are not anagrams")

enter the 1st string : hello
enter the 2nd string : world
they are not anagrams

Q5. Write a code to find all occurence of a given substring in another string.

In [21]:
string1 = "patiently"
sub_string = "pat"
if sub_string in string1:
    print("yes")
else:
    print("No")

yes

Q6. Write a code to perform basic string compression using the counts of a repeated characters.

In [ ]:
s1= "aaabbbbccccdddefff"
compressed_string= ""
count=1
for i in range(1, len(s1)):
  if s1[i] == s1[i-1]:
    count+=1
  else:
    compressed_string += s1[i-1] + str(count)
    count=1
compressed_string += s1[-1] + str(count)
compressed_string

'a3b4c4d3e1f3'

Q7. Write a code to determine if a string has all unique characters.

In [ ]:
s1= "himalayas"
x= list(s1)
y= list(set(s1))
x.sort()
y.sort()
if x==y:
  print("unique")
else:
  print("not unique")

not unique

In [ ]:
s1= "techno"
x= list(s1)
y= list(set(s1))
x.sort()
y.sort()
if x==y:
  print("unique")
else:
  print("not unique")

unique

Q8. Write a code to convert a string to uppercase or lowercase.

In [ ]:
uppercase = input("enter a string: ")
s2=""
for i in uppercase:
  i=i.upper()
  s2 += i
s2

enter a string: Rashi Agrawal

'RASHI AGRAWAL'

In [ ]:
lowercase = input("enter a string: ")
s2= ""
for i in lowercase:
  i=i.lower()
  s2 += i
s2

enter a string: My namE IS RasHi

'my name is rashi '

Q9. Write a code to count the number of words in a string.

In [ ]:
s1= input("enter a sentence: ")
count = 0
s2= s1.split()
for i in s2:
  count +=1
print("the number of words in the string is : ", count)

enter a sentence: my name is rashi agrawal
the number of words in the string is :  5

Q10. Write a code to concatenate the two strings without using the + operator.

In [ ]:
s1 = "rashi"
s2 = "agrawal"
print (s1,s2)

rashi agrawal

Q11. Write a code to remove all occurence of a specific element from a list.

In [ ]:
list1=[ 1,1,3,2,7,67,5,34,7,4]
#to remove the occurence of '7'from the list;
for i in list1:
  if i == 7:
    list1.remove(i)
list1

[1, 1, 3, 2, 67, 5, 34, 4]

Q12. Implement a code to find the second largest number in a given list of integers.

In [ ]:
list1= [23,66,57,45,3,5,7,8,56,90]
print(list1)
list1.sort()
print('the 2nd largest number in the list is: ', list1[-2])

[23, 66, 57, 45, 3, 5, 7, 8, 56, 90]
the 2nd largest number in the list is:  66

Q13. Create a code to count the occurence of each element in a list and return a dictionary with elements as keys and their counts as values.

In [ ]:
list1 = ["apple", "mango" , "banana" , "apple" , "mango", "banana", "grapes"]
dictionary={}
list2=sorted(list1)
count=1

for i in range(0,len(list2)):
  if list2[i]== list2[i-1]:
    count+=1
    s1={list2[i]:count}
  else:
    dictionary
    dictionary.update(s1)
    s1={list2[i]:count}
  count=1
dictionary

{'mango': 2, 'apple': 2, 'banana': 2, 'grapes': 1}

Q14. Write a code to reverse a list in-place without using any built-in reverse function.

In [ ]:
list1

['apple', 'mango', 'banana', 'apple', 'mango', 'banana', 'grapes']

In [ ]:
list1[::-1]

['grapes', 'banana', 'mango', 'apple', 'banana', 'mango', 'apple']

Q15. Implement a code to find and remove duplicates from a list while preserving the original order of elements.

In [15]:
list1

['apple', 'mango', 'banana', 'apple', 'mango']

In [17]:
edited_list =[]
for i in list1:
    if i not in edited_list:
        edited_list.append(i)
print(f"edited list is {edited_list}")

edited list is ['apple', 'mango', 'banana']

Q16. Create a code to check if a given list is sorted(either in ascending or descending order ) or not.

In [ ]:
list1=[4,787,434,67,45,4,98,70]
if list1==sorted(list1):
  print("the list is in ascending order.")
elif list1 == sorted(list1,reverse=True):
  print("the list is in descending order.")
else:
  print("the list is not sorted.")

the list is not sorted.

In [ ]:
list1=[23,45,67,89,234,567]
if list1==sorted(list1):
  print("the list is in ascending order.")
elif list1 == sorted(list1,reverse=True):
  print("the list is in descending order.")
else:
  print("the list is not sorted.")

the list is in ascending order.

In [ ]:
list1=[987,765,654,543,432,98,65,43,8,3]
if list1==sorted(list1):
  print("the list is in ascending order.")
elif list1 == sorted(list1,reverse=True):
  print("the list is in descending order.")
else:
  print("the list is not sorted.")

the list is in descending order.

Q17. Write a code to merge two sorted list into a single sorted list.

In [ ]:
list1= [14,67,5,3,78,98]
list2= [45,34,64,98,76,4]
list3= (list1)+(list2)
list3= sorted(list3)
list3

[3, 4, 5, 14, 34, 45, 64, 67, 76, 78, 98, 98]

Q18. Implement a code to find the intersection of two given lists .

In [ ]:
list1 = [23,45,67,89,4,34,67,34,23,90]

In [ ]:
list2 = [45,67,4,54,32,65,87,5,90,43]

In [ ]:
list3 = set(list1) & set(list2)
print("intersection of the two list is : ", list(list3))

intersection of the two list is :  [90, 67, 4, 45]

Q19. Create a code to find the union of to lists without duplicates.

In [ ]:
list1

[23, 45, 67, 89, 4, 34, 67, 34, 23, 90]

In [ ]:
list2

[45, 67, 4, 54, 32, 65, 87, 5, 90, 43]

In [ ]:
list3= set(list1) | set(list2)
print("the union of the two list is : ", list(list3))

the union of the two list is :  [65, 67, 4, 5, 23, 87, 89, 90, 32, 34, 43, 45, 54]

Q20. Write a code to shuffle a given list randomly without using any built-in shuffle functions.

In [7]:
import random

lis = [40,30,130,50,39,20,50,604,30]
for i in range(len(lis)-1,0,-1):
    index = random.randint(0,i)
    lis[i],lis[index] = lis[index],lis[i]
print("shuffled list = ",lis)

shuffled list =  [604, 50, 130, 20, 39, 30, 50, 40, 30]

Q21. Write a code that takes two tuples as input and returns a new tuple containing elements that are common to both input tuples.

In [ ]:
tuple1 = (50,60,70,80,89,90,60,57,87)
tuple2 = (70,78,86,90,57,87,57,87)
tuple3 = set(tuple1) & set(tuple2)
print("the common elements in the tuples are: ", tuple(tuple3))

the common elements in the tuples are:  (57, 90, 70, 87)

Q22. Create a code that prompts the user to enter two sets of integers seperated by commas. then, print the intersection of these two sets.

In [ ]:
x1 = (input("enter 1st set of integers separated by commas : "))
x2 = (input("enter 1st set of integers : "))
x1 = set((x1.split(",")))
x2 = set((x2.split(",")))
x3 = x1 & x2
print(" the intersection between the sets is : ", x3)

enter 1st set of integers separated by commas : 30,40,50,60,4
enter 1st set of integers : 50,60,30,4,3,2,9
 the intersection between the sets is :  {'4', '30', '50', '60'}

Q23.  Write a code to concatenate two tuples. The functions should take two tuples as input and return a new tuple containing elements from both input tuples.

In [ ]:
tuple1 = ( 30, 40, "pari", "ds" )
tuple2 = ( 50, 60, "princess", "ds" )
tuple3 = tuple1 + tuple2
tuple3

(30, 40, 'pari', 'ds', 50, 60, 'princess', 'ds')

Q24. Develop a code that prompts the user to input two set of strings. Then, print the elements that are present in 1st set but not in the second set.

In [ ]:
set1 = input("enter strings : ")
set2 = input("enter strings : ")
x1 = set1.split(",")
x2 = set2.split(",")
x3 = set(x1)-set(x2)
print(" the strings present in 1st set but not in the 2nd set are :")
x3

enter strings : potato,onion,tomato,brinjal,drumsticks
enter strings : onion,garlic,eggplant,brinjal
 the strings present in 1st set but not in the 2nd set are :

{'drumsticks', 'potato', 'tomato'}

Q25. Create a code that takes a tuple and two integers as input. The function should repeat a new tuple containing the elemnents from the original tuple within a specified range of indices.

In [ ]:
tuple1 = ( 40,50,30,20)
int1 = (40)
int2 = (50)
new_tuple = list(tuple1)
new_tuple.append(int1)
new_tuple.append(int2)
new_tuple = tuple(new_tuple)
new_tuple

(40, 50, 30, 20, 40, 50)

 Q26. Write a code to that prompts the user to input two sets of characters. Then, print the union of these two sets

In [ ]:
set1 = input(" enter characters : ")
set2 = input(" enter more characters : ")
set3 = set( set1.split() + set2.split() )
set3

 enter characters : r a s h i
 enter more characters : a g r a w a l

{'a', 'g', 'h', 'i', 'l', 'r', 's', 'w'}

Q27. Develop a code that takes a tuple of integer as input. The function should return the maximum and the minimum values from the tupple using tuple unpacking.

In [ ]:
tuple1 = (40,50,30,20,50)
max(tuple1)

50

In [ ]:
min(tuple1)

20

Q28. Create a code that defines two sets of integers. Then, print the union, intersection, difference of these two sets.

In [ ]:
s1 = {20,50,60,29,67,48,30}
s2 = {50,60,20,98,26,45,10}
print("the unioun of the sets are : ", s1|s2)
print(" the intersection is : ", s1&s2)
print(" the difference is : ", s1-s2)

the unioun of the sets are :  {98, 67, 10, 45, 48, 50, 20, 26, 60, 29, 30}
 the intersection is :  {50, 20, 60}
 the difference is :  {48, 67, 29, 30}

Q29. Write a code that takes a tuple and an element as input. the function should return the count of occurence of a given element in the tuple.

In [ ]:
tuple1 = (30,40,20,50,60,50,40,10)
element1 = 40
tuple1.count(element1)

2

Q30. Develop a code that prompts the user to input two sets of strings. Then, print the symmetric difference of these to sets.

In [ ]:
s1 = input(" enter strings : ")
s2 = input(" enter strings : ")
sym_diff = set(s1.split(","))^set(s2.split(","))
print(" the symmetric difference between the sets are: ")
sym_diff

 enter strings : my,name,is,this,is,my,fav,toy
 enter strings : my,fav,toy,badminton,singing,you
 the symmetric difference between the sets are:

{'badminton', 'is', 'name', 'singing', 'this', 'you'}

Q31. Write a code that takes a list of words as input and returns a dictionary where the keys are unique words and the values are the frequencies of those words in the input list.

In [ ]:
words = ["tomato","potato","tomato","potato","potato","onion","carrot","carrot","raddish","raddish"]
count=1
word = sorted(words)
dictionary={}
for i in range(1,len(words)):
    if word[i] == word[i-1]:
        count+=1
    else:
        dictionary[word[i-1]]=count
        count=1
    dictionary[word[i]]=count
print(dictionary)

{'carrot': 2, 'onion': 1, 'potato': 3, 'raddish': 2, 'tomato': 2}

  Q32. Write a code that takes two dictionaries as an input and merges them into a single dictionary. If there are common keys, the value should be added together.

In [ ]:
dict1 = {"name":"rashi","study":"data science","interests":"singing"}
dict2 = {"age":20, "interests":"travelling"}
for key1,value1 in dict1.items():
  for key2,value2 in dict2.items():
    if key1==key2:
      dict2[key1]= (value1,value2)
final_dictionary = dict1 | dict2
print("the final dict is : ",final_dictionary)

the final dict is :  {'name': 'rashi', 'study': 'data science', 'interests': ('singing', 'travelling'), 'age': 20}

Q33. Write a code to access a value in a nested dictionary. The function should take the dictionary and a list of keys as input, and return the corresponding . If any of the keys do not exist in the dictionary, the function should return none.

In [4]:
dict1 = {"file1":{"name":"rashi","course":"data_science"},"file2":{"age":"20","study":"bsc"}}
list1= ["file1","name"]
value = dict1
for key in list1:
    if key in value:
        value = value[key]
    else:
        value = None
print(value)

rashi

In [2]:

nested_dict = {'a': 1,'b': {'c': 2,'d': {'e': 3}}}

keys = ['b', 'd', 'e']
value = nested_dict
for key in keys:
    if key in value:
        value = value[key]
    else:
        value = None
        break
print(value)

keys = ['b', 'd', 'f']
value = nested_dict
for key in keys:
    if key in value:
        value = value[key]
    else:
        value = None
        break
print(value)

3
None

Q34. Write a code that takes a dictionary as input and returns a sorted version of it based on the values. You can choose whether to sort in ascending or descending order.

In [ ]:
dict1 = {"name":"rashi","study":"data science","interests":"singing"}
dict2 = sorted(dict1.items(),key=lambda items:items[1])
dict2

[('study', 'data science'), ('name', 'rashi'), ('interests', 'singing')]

Q35. Write a code that inverts a dictionary, swapping keys and values. Ensure that the inverted dictionary handles cases where multiple keys have the same value by storing the keys as a list in the inverted dictionary.

In [ ]:
dict1

{'name': 'rashi', 'study': 'data science', 'interests': 'singing'}

In [ ]:
dict2 ={}
for k,v in dict1.items():
    k,v = v,k
    dict2[k] = v
dict2

{'rashi': 'name', 'data science': 'study', 'singing': 'interests'}